### ISSUE TITLE
Please excuse me, I don't know how to contact you otherwise.

### ISSUE THREAD

**Issue by SolsticeProjekt** [cdjc/goto#4]
... what a very phytonic way of approaching someone. lol

I'm not much into Open Source and don't know how things work, so I have to ask.
I'm working on some python project, which I am probably going to release at some point.

I'm an assembly programmer at heart and discovered my love for python years ago,
but I'm not going to change my programming habits. I'm missing a jmp instruction,
and instead of spending time figuring out how to do it myself,
I remembered that there were some. So now I'm here.

What I wanted to know, is, if it's okay if I include your code *as is* into my own script,
with the proper license at the top of course, visually separated.

The reason is simply that I want to release *only a single script file which anyone can use*,
not counting a mandatory package which has to be installed,
which is a library of a trading platform. Far too complex to just all put into a single script.

So ... I wanted to ask if that's okay, as long as credits are given where credits are due?

Thank you!

**Comment by cdjc** [comment]
Sure. Go for it.
Caveats:

1. There are almost certainly a number of better ways of doing what you want (a list or dictionary of functions perhaps?). 
2. Fiddling with the bytecode is non-portable to other Pythons, and can (and will!) break from time to time with newer versions of cPython. I haven't looked at this code in a long time. It might already fail with newer versions of Python.

Also please let me offer some friendly advice: it can be healthy to challenge your programming habits from time to time. Don't let your habits stop you from growing as a programmer. There are new programming discoveries out there waiting for you.

**Comment by SolsticeProjekt** [comment]
Mate. I know you mean well, but what's with that assumption?

You talk to me like I wouldn't be doing stuff like this for over 30 years already. I've been writing self modifying code on a 386, aka since I've been a teenager. I've been writing a fractal zoom using self modifying code using both processors on the NDS. I've helped the freepascal developers making the code self-aware about which processor it's running on.

Any new language I find, I try to run compiled assembly code in. If I can't, I dismiss it. (My peeks into WebAssembly were interesting). I've scavenged through the byterun code, discovering that they've been missing an Opcode and fixed the issue.

I write full screen high resolution software rendered metaballs which burn your CPU
and my fixed pattern matching code is bottlenecked by my 5900HS' memoryIO and cache performance.

Nothing else.

I know that, because my i5 7300HQ with slower, single channel RAM,
scans through the same amount of data 30ms faster. Insanity. 

So ...

Mate! Thank you for your friendly advice, but maybe you should take mine:

Habits are a form of Automaticity and Automaticity has, as one consequence, thoughtlessness.
It's good to have *standards*, but bad to have *habits*. Not using goto should not be anyone's standard.

The problem here is not goto, it's the inability of the programmer to handle it. Instead of finding ways to teach
future programmers how to structure code in their minds, humanity went the easy route and decided to rather
avoid the issue and claim it's *bad*, solely nobody wanted to improve the situation.

Another case in point: Pointers.


Embrace your Gotos, mate!
Embrace them!

**Comment by cdjc** [comment]
I more-or-less agree with you. And I also was writing self-modifying code as a teenager (6502). And of course I agree with you about goto - I think most people familiar with assembly would. I'm not against the goto statement; I did write this goto decorator after all! Go forth and JMP with wild abandon!
