### ISSUE TITLE
Works on Python 3.9 and how to install?

### ISSUE THREAD

**Issue by RestOp** [cdjc/goto#5]
Hi,

how to installi it on Python 3.9 ?

Thanks!

**Comment by cdjc** [comment]
No install is necessary. Just add goto.py to your directory and import it. I haven't tested it on Python 3.9+

**Comment by RestOp** [comment]
> No install is necessary. Just add goto.py to your directory and import it. I haven't tested it on Python 3.9+

Hello
I have tested. Do not work.

**Comment by cdjc** [comment]
OK. When I get time I'll take a look. It's not high priority right now though.

**Comment by cdjc** [comment]
Upgrade to python 3.11 and use the new version. Should work.
