### ISSUE TITLE
Reverse construction

### ISSUE THREAD

**Issue by mister-proger** [cdjc/goto#8]
It would be interesting to add `comefrom`. `goto` skips the code, while this construction will roll back code state.

**Comment by cdjc** [comment]
@mister-proger I'm not sure what you mean by "roll back code state". The `comefrom` statement simply turns a `label` from a no-op into a `goto` to the `comefrom`. If a `label` has a `comefrom` as well as one or more `goto`s, those `goto`s will go to the `label`'s `comefrom`. Simple :-)
Happy to consider a `comefrom` pull request, but it's not on the agenda right now.
